// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnKiLmDiBf0yydUdUhVNNjEEoxKR9_9RY',
    appId: '1:1091225187710:web:6da3b5d773ad78ba7c6f2f',
    messagingSenderId: '1091225187710',
    projectId: 'veg-inventory',
    authDomain: 'veg-inventory.firebaseapp.com',
    storageBucket: 'veg-inventory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA6_Ut1YlzAL4f-w9V0PDAWHaqKkp6Kaw',
    appId: '1:1091225187710:android:d3eb82ae7d99330f7c6f2f',
    messagingSenderId: '1091225187710',
    projectId: 'veg-inventory',
    storageBucket: 'veg-inventory.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjk4an5zAo1iDE4kXWFxGZZYag6WxvoQ',
    appId: '1:1091225187710:ios:f0b56b2e2c682c157c6f2f',
    messagingSenderId: '1091225187710',
    projectId: 'veg-inventory',
    storageBucket: 'veg-inventory.firebasestorage.app',
    iosBundleId: 'com.example.vegShopManager',
  );
}
