class AppConstants {
  static const String appName = 'GreenChain';

  /// The single super-admin (app owner). Only this account sees the in-app
  /// Settings screen (language + theme). Compared case-insensitively.
  static const String ownerEmail = 'mohsin.sapra@gmail.com';
  
  static const Map<String, String> predefinedShops = {
    'shop1': 'Shop 1 - Downtown',
    'shop2': 'Shop 2 - Mall',
    'shop3': 'Shop 3 - Suburb',
  };

  static const Map<String, String> shopPasswords = {
    'shop1': 'shop1pass',
    'shop2': 'shop2pass',
    'shop3': 'shop3pass',
  };
  
  static const String adminCredential = 'admin';
  static const String adminPassword = 'admin123';
  
  static const String hiveBoxMissingItems = 'missing_items';
  static const String hiveBoxShoppingHistory = 'shopping_history';
  static const String hiveBoxAuth = 'auth';
  static const String hiveBoxUsers = 'users';
  
  static const String currentUserKey = 'current_user';
  static const String currentShopKey = 'current_shop';

  // Predefined items organized by category
  static const Map<String, List<String>> predefinedItems = {
    'Vegetables': [
      'Apio',
      'Bola de apio',
      'Aguacate',
      'Aguacate UND',
      'Alcachofa',
      'Ajo Tierno',
      'Ajo Seco',
      'Ajo Malla',
      'Borraja',
      'Acelga',
      'Bonito',
      'Berenjena N',
      'Berenjena R',
      'Brócoli',
      'Champiñones',
      'Seta',
      'Calabacín',
      'Calabaza',
      'Coliflor',
      'Col De hoja',
      'Repollo',
      'Col China',
      'Cebolla Blanca',
      'Cebolla Normal',
      'Cebolla Dulce',
      'Cebolla Tierna',
      'Cebolla Roja',
      'Cardo',
      'Endivia',
      'Espinaca',
      'Jengibre',
      'Lechuga Romana',
      'Iceberg',
      'Batavia',
      'Cogollo',
      'Escarola',
      'Roble',
      'Espárrago',
      'Espárrago Blanco',
      'Eneldo',
      'Cilantro',
      'Perejil',
      'Remolacha',
      'Chirivía',
      'Nabos',
      'Rábanos',
      'Judía',
      'Judía Extra',
      'Pepino',
      'Puerro',
      'Patata Roja',
      'Patata Lavada',
      'Patata 5 Kilo',
      'Patata 2 Kilo',
      'Bisalto',
      'Hinojo',
      'Romanesco',
      'Habas',
      'Zanahoria',
      'Robellones',
      'Hierbabuena',
      'Boniato',
      'Cebolla Seca',
    ],
    'Tomatoes': [
      'Tomate Oferta',
      'Tomate Daniela',
      'Tomate Pera',
      'Tomate Rama',
      'Tomate Raf',
      'Tomate Pink',
      'Tomate Ensalada',
      'Tomate Rosa',
      'Tomate Cherry',
      'Tomate Kumato',
    ],
    'Peppers': [
      'Oliva Negra',
      'Oliva Relleno',
      'Oliva Blanca',
      'Pimiento Rojo',
      'Pimiento Rojo 2',
      'Pimiento Italiano',
      'Pimiento Italiano 2',
      'Pim Palermo',
      'California',
      'Pim Verde',
      'Pim Africano',
      'Padrón',
      'Picante',
      'Oliva Manzanilla',
      'Oliva Hechizos',
      'Oliva Revuelto',
    ],
    'Tropical & Exotic': [
      'Limón',
      'Lima',
      'Macho Verde',
      'Plátano Maduro',
      'Yuca',
      'Coquillo',
      'Banana',
      'Plátano',
      'Chirimoya',
      'Mango',
      'Mango Extra',
      'Papaya',
      'Piña Normal',
      'Piña Monte',
    ],
    'Stone Fruits': [
      'Ciruela Roja',
      'Ciruela Amarilla',
      'Ciruela Claudia',
      'Ciruela President',
      'Cereza 1st',
      'Cereza 2nd',
      'Albaricoque Oferta',
      'Albaricoque 1st',
      'Albaricoque 2nd',
      'Albaricoque Rojo',
      'Melocotón Calanda',
      'Melocotón Oferta',
      'Melocotón 2nd',
      'Melocotón Rojo 1',
      'Melocotón Rojo 2',
      'Melocotón Blanco',
      'Pavía Oferta',
      'Pavía 1st',
      'Pavía 2nd',
      'Pavía Blanco',
      'Níspero',
      'Paraguayo Oferta',
      'Paraguayo 1st',
      'Paraguayo 2nd',
    ],
    'Citrus': [
      'Granada',
      'Granada Extra',
      'Mandarina Oferta',
      'Mandarina 1st',
      'Mandarina Valencia',
      'Mandarina Hoja',
      'Naranja Mesa',
      'Naranja Oferta',
      'Naranja Navel',
      'Naranja Bolsa 2k',
      'Naranja Bolsa 4k',
      'Pomelo',
      'Naranja Ripoll',
      'Mandarina',
      'Mandarina Extra',
    ],
    'Apples & Pears': [
      'Manzana Oferta',
      'Golden 1st',
      'Golden 2nd',
      'Fuji 1st',
      'Fuji 2nd',
      'Roja 1st',
      'Roja 2nd',
      'Royal Gala 1st',
      'Royal Gala 2nd',
      'Verde Doncella',
      'Pink Lady',
      'Granny',
      'Reineta',
      'Pera Oferta',
      'Conferencia 1st',
      'Conferencia 2nd',
      'Pera Agua',
      'Pera Limonera',
      'Pera Roma',
      'Pera Ercolina',
      'Manzana Chantecler',
    ],
    'Other Fruits': [
      'Kiwi Oferta',
      'Kiwi Zespri',
      'Kiwi Italiano',
      'Kiwi Gold',
      'Caqui 1st',
      'Caqui 2nd',
      'Melón',
      'Melón Galia',
      'Membrillo',
      'Nueces',
      'Castaña',
      'Dátiles',
      'Sandía Rayada',
      'Sandía Negra',
      'Sandía Rollo',
      'Uva Roja',
      'Uva Blanca',
      'Uva Extra',
      'Garnacha',
      'Persimón',
      'Sanguina',
      'Fresa',
      'Fresa Extra',
      'Melón Bollo',
      'Uva sin pepita',
      'Higos',
    ],
    'Accessories': [
      'Bolsa Verde',
      'Bolsa Blanca',
      'Bolsa Rollo',
      'Guantes',
    ],
  };

  // Flattened list of all items for search
  static List<String> get allPredefinedItems {
    return predefinedItems.values.expand((items) => items).toList()..sort();
  }

  /// The exact order items appear on the paper stock sheet (Verduras col 1 →
  /// Verduras col 2 → Frutas col 3). Seeding assigns sortOrder by this order so
  /// a fresh install lists items the same way the shop's paper does. Any
  /// catalog item not in this list is appended after, keeping its group order.
  static const List<String> paperOrder = [
    'Apio', 'Aguacate', 'Aguacate UND', 'Alcachofa', 'Ajo Malla', 'Ajo Seco',
    'Acelga', 'Borraja', 'Berenjena N', 'Berenjena R', 'Brócoli', 'Champiñones',
    'Seta', 'Calabacín', 'Calabaza', 'Coliflor', 'Col De hoja', 'Boniato',
    'Ajo Tierno', 'Cebolla Tierna', 'Cardo', 'Endivia', 'Espinaca', 'Jengibre',
    'Lechuga Romana', 'Iceberg', 'Batavia', 'Cogollo', 'Escarola', 'Roble',
    'Espárrago', 'Repollo', 'Nabos', 'Remolacha', 'Chirivía', 'Rábanos', 'Judía',
    'Judía Extra', 'Limón', 'Lima', 'Macho Verde', 'Plátano Maduro', 'Yuca',
    'Pimiento Rojo', 'Pimiento Rojo 2', 'Pimiento Italiano', 'Pim Palermo',
    'California', 'Padrón', 'Picante', 'Pepino', 'Puerro', 'Pomelo',
    'Tomate Oferta', 'Tomate Daniela', 'Tomate Pera', 'Tomate Rama', 'Tomate Raf',
    'Tomate Pink', 'Tomate Ensalada', 'Tomate Rosa', 'Tomate Cherry', 'Banana',
    'Plátano', 'Ciruela Roja', 'Ciruela Amarilla', 'Ciruela Claudia', 'Fresa',
    'Fresa Extra', 'Cereza 2nd', 'Kiwi Oferta', 'Kiwi Zespri', 'Kiwi Italiano',
    'Kiwi Gold', 'Caqui 1st', 'Caqui 2nd', 'Mango', 'Mango Extra', 'Melón',
    'Melón Bollo', 'Manzana Oferta', 'Golden 1st', 'Golden 2nd', 'Fuji 1st',
    'Fuji 2nd', 'Roja 1st', 'Roja 2nd', 'Royal Gala 1st', 'Royal Gala 2nd',
    'Verde Doncella', 'Pink Lady', 'Granny', 'Reineta', 'Manzana Chantecler',
    'Nueces', 'Dátiles', 'Castaña', 'Granada', 'Granada Extra', 'Pera Oferta',
    'Conferencia 2nd', 'Pera Agua', 'Pera Limonera', 'Pera Roma', 'Pera Ercolina',
    'Papaya', 'Chirimoya', 'Piña Normal', 'Piña Monte', 'Uva Blanca',
    'Uva sin pepita', 'Uva Roja', 'Garnacha', 'Naranja Bolsa 2k',
    'Naranja Bolsa 4k', 'Naranja Mesa', 'Naranja Ripoll', 'Naranja Oferta',
    'Mandarina Extra', 'Mandarina Hoja', 'Mandarina Valencia', 'Mandarina Oferta',
    'Mandarina', 'Patata Lavada', 'Patata Roja', 'Patata 5 Kilo', 'Cebolla Seca',
    'Cebolla Roja', 'Cebolla Dulce', 'Zanahoria', 'Oliva Negra', 'Oliva Revuelto',
    'Oliva Manzanilla', 'Oliva Hechizos', 'Higos',
  ];
}