/// Hotlinked produce images (Wikipedia/Wikimedia thumbnails), keyed by
/// catalog item name. Mirrored to Firestore `catalogItems.imageUrl`;
/// used as seed data and as an offline fallback in the UI.
abstract class ItemImages {
  static const Map<String, String> byName = {
    'Apio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Illustration_Apium_graveolens0.jpg/330px-Illustration_Apium_graveolens0.jpg',
    'Bola de apio': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Illustration_Apium_graveolens0.jpg/330px-Illustration_Apium_graveolens0.jpg',
    'Aguacate': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Persea_americana1.JPG/330px-Persea_americana1.JPG',
    'Aguacate UND': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Persea_americana1.JPG/330px-Persea_americana1.JPG',
    'Alcachofa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/P1000578_Galactites_tomentosa_%28Compositae%29_Flowers.JPG/330px-P1000578_Galactites_tomentosa_%28Compositae%29_Flowers.JPG',
    'Ajo Tierno': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/CSA-Red-Spring-Onions.jpg/330px-CSA-Red-Spring-Onions.jpg',
    'Ajo Seco': 'https://upload.wikimedia.org/wikipedia/commons/3/39/Allium_sativum_Woodwill_1793.jpg',
    'Ajo Malla': 'https://upload.wikimedia.org/wikipedia/commons/3/39/Allium_sativum_Woodwill_1793.jpg',
    'Borraja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/224_Borrago_officinalis_L.jpg/330px-224_Borrago_officinalis_L.jpg',
    'Acelga': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Swiss_Chard.jpg/330px-Swiss_Chard.jpg',
    'Bonito': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Calabaza_Vines_%28Flor_de_Auyama%29.jpg/330px-Calabaza_Vines_%28Flor_de_Auyama%29.jpg',
    'Berenjena N': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/330px-Solanum_melongena_24_08_2012_%281%29.JPG',
    'Berenjena R': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Solanum_melongena_24_08_2012_%281%29.JPG/330px-Solanum_melongena_24_08_2012_%281%29.JPG',
    'Brócoli': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Broccoli_bunches.jpg/330px-Broccoli_bunches.jpg',
    'Champiñones': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/ChampignonMushroom.jpg/330px-ChampignonMushroom.jpg',
    'Seta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Austernseitling-1.jpg/330px-Austernseitling-1.jpg',
    'Calabacín': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/0.2014_Cucurbita_pepo_subsp._pepo_convar._giromontiina_-_Sanok.JPG/330px-0.2014_Cucurbita_pepo_subsp._pepo_convar._giromontiina_-_Sanok.JPG',
    'Calabaza': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Calabaza_Vines_%28Flor_de_Auyama%29.jpg/330px-Calabaza_Vines_%28Flor_de_Auyama%29.jpg',
    'Coliflor': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Bloemkool.jpg/330px-Bloemkool.jpg',
    'Col De hoja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Boerenkool.jpg/330px-Boerenkool.jpg',
    'Repollo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Kalkar_-_Wei%C3%9Fkohl_01_ies.jpg/330px-Kalkar_-_Wei%C3%9Fkohl_01_ies.jpg',
    'Col China': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/%ED%95%AD%EC%95%94%EB%B0%B0%EC%B6%94.jpg/330px-%ED%95%AD%EC%95%94%EB%B0%B0%EC%B6%94.jpg',
    'Cebolla Blanca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Two_colors_of_onions.jpg/330px-Two_colors_of_onions.jpg',
    'Cebolla Normal': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Two_colors_of_onions.jpg/330px-Two_colors_of_onions.jpg',
    'Cebolla Dulce': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Two_colors_of_onions.jpg/330px-Two_colors_of_onions.jpg',
    'Cebolla Tierna': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/CSA-Red-Spring-Onions.jpg/330px-CSA-Red-Spring-Onions.jpg',
    'Cebolla Roja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Red_Onion_on_White.JPG/330px-Red_Onion_on_White.JPG',
    'Cebolla Seca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Two_colors_of_onions.jpg/330px-Two_colors_of_onions.jpg',
    'Cardo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Cynara_cardunculus0.jpg/330px-Cynara_cardunculus0.jpg',
    'Endivia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Endive_p1160063.jpg/330px-Endive_p1160063.jpg',
    'Espinaca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Illustration_Spinacia_oleracea0.jpg/330px-Illustration_Spinacia_oleracea0.jpg',
    'Jengibre': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Koeh-146-no_text.jpg/330px-Koeh-146-no_text.jpg',
    'Lechuga Romana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Romaine_lettuce.jpg/330px-Romaine_lettuce.jpg',
    'Iceberg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Iceberg_lettuce_%28IJssla_krop%29.jpg/330px-Iceberg_lettuce_%28IJssla_krop%29.jpg',
    'Batavia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Batavia.JPG/330px-Batavia.JPG',
    'Cogollo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Starr_070730-7911_Lactuca_sativa.jpg/330px-Starr_070730-7911_Lactuca_sativa.jpg',
    'Escarola': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Cichorium_endivia_-_Botanischer_Garten_Mainz_IMG_5453.JPG/330px-Cichorium_endivia_-_Botanischer_Garten_Mainz_IMG_5453.JPG',
    'Roble': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Red_leaf_lettuce_J1.JPG/330px-Red_leaf_lettuce_J1.JPG',
    'Espárrago': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Illustration_Asparagus_officinalis0b.jpg/330px-Illustration_Asparagus_officinalis0b.jpg',
    'Espárrago Blanco': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Illustration_Asparagus_officinalis0b.jpg/330px-Illustration_Asparagus_officinalis0b.jpg',
    'Eneldo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Dill_seed_tilli_siemen.jpg/330px-Dill_seed_tilli_siemen.jpg',
    'Cilantro': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Coriandrum_sativum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-193.jpg/330px-Coriandrum_sativum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-193.jpg',
    'Perejil': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Petroselinum_crispum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-103.jpg/330px-Petroselinum_crispum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-103.jpg',
    'Remolacha': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Beta_vulgaris_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-167.jpg/330px-Beta_vulgaris_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-167.jpg',
    'Chirivía': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Parsnips.JPG/330px-Parsnips.JPG',
    'Nabos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Brassica_rapa_plant.jpg/330px-Brassica_rapa_plant.jpg',
    'Rábanos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/26_Raphanus_sativus_L.jpg/330px-26_Raphanus_sativus_L.jpg',
    'Judía': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Phaseolus_vulgaris.jpg/330px-Phaseolus_vulgaris.jpg',
    'Judía Extra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Phaseolus_vulgaris.jpg/330px-Phaseolus_vulgaris.jpg',
    'Pepino': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Cucumis_sativus_0002.JPG/330px-Cucumis_sativus_0002.JPG',
    'Puerro': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Poireaux.JPG/330px-Poireaux.JPG',
    'Patata Roja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/S._tuberosum-5.JPG/330px-S._tuberosum-5.JPG',
    'Patata Lavada': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/S._tuberosum-5.JPG/330px-S._tuberosum-5.JPG',
    'Patata 5 Kilo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/S._tuberosum-5.JPG/330px-S._tuberosum-5.JPG',
    'Patata 2 Kilo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/S._tuberosum-5.JPG/330px-S._tuberosum-5.JPG',
    'Bisalto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Blauwschokker_Kapucijner_rijserwt_Pisum_sativum.jpg/330px-Blauwschokker_Kapucijner_rijserwt_Pisum_sativum.jpg',
    'Hinojo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Foeniculum_vulgare_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-148.jpg/330px-Foeniculum_vulgare_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-148.jpg',
    'Romanesco': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Romanesco_broccoli_%28Brassica_oleracea%29.jpg/330px-Romanesco_broccoli_%28Brassica_oleracea%29.jpg',
    'Habas': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Illustration_Vicia_faba1.jpg/330px-Illustration_Vicia_faba1.jpg',
    'Zanahoria': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Bunches_of_carrots.jpg/330px-Bunches_of_carrots.jpg',
    'Robellones': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Lactarius_deliciosus.jpg/330px-Lactarius_deliciosus.jpg',
    'Hierbabuena': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Mentha_viridis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-096.jpg/330px-Mentha_viridis_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-096.jpg',
    'Boniato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/5aday_sweet_potato.jpg/330px-5aday_sweet_potato.jpg',
    'Tomate Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Tomate Daniela': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Tomate Pera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Plum_Tomatoes%2C_Lexington_MA.jpg/330px-Plum_Tomatoes%2C_Lexington_MA.jpg',
    'Tomate Rama': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg',
    'Tomate Raf': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Tomate Pink': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Tomate Ensalada': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Tomate Rosa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Tomate Cherry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Tomates_cerises_Luc_Viatour.jpg/330px-Tomates_cerises_Luc_Viatour.jpg',
    'Tomate Kumato': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Bright_red_tomato_and_cross_section02.jpg/330px-Bright_red_tomato_and_cross_section02.jpg',
    'Oliva Negra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg/330px-Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg',
    'Oliva Relleno': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg/330px-Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg',
    'Oliva Blanca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg/330px-Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg',
    'Oliva Manzanilla': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg/330px-Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg',
    'Oliva Hechizos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg/330px-Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg',
    'Oliva Revuelto': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg/330px-Olives%28LUCQUES%29_Cl_J_Weber_%2823184151061%29.jpg',
    'Pimiento Rojo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg/330px-Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg',
    'Pimiento Rojo 2': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg/330px-Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg',
    'Pimiento Italiano': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Pickled_friggitelli.jpg/330px-Pickled_friggitelli.jpg',
    'Pimiento Italiano 2': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Pickled_friggitelli.jpg/330px-Pickled_friggitelli.jpg',
    'Pim Palermo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg/330px-Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg',
    'California': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg/330px-Pimiento_morr%C3%B3n_%28Capsicum_annuum%29.jpg',
    'Pim Verde': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Pickled_friggitelli.jpg/330px-Pickled_friggitelli.jpg',
    'Pim Africano': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg/330px-Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg',
    'Padrón': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Pementos_de_Padron.jpg/330px-Pementos_de_Padron.jpg',
    'Picante': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg/330px-Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg',
    'Limón': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Citrus_x_limon_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-041.jpg/330px-Citrus_x_limon_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-041.jpg',
    'Lima': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Lime_-_whole_and_halved.jpg/330px-Lime_-_whole_and_halved.jpg',
    'Macho Verde': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Banana.plant.kewgardens.arp.jpg/330px-Banana.plant.kewgardens.arp.jpg',
    'Plátano Maduro': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Banana.plant.kewgardens.arp.jpg/330px-Banana.plant.kewgardens.arp.jpg',
    'Yuca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Manihot_esculenta_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-090.jpg/330px-Manihot_esculenta_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-090.jpg',
    'Coquillo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Owoce_Orzech_kokosowy.jpg/330px-Owoce_Orzech_kokosowy.jpg',
    'Banana': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Bananas.jpg/330px-Bananas.jpg',
    'Plátano': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Platano_de_canarias.jpg/330px-Platano_de_canarias.jpg',
    'Chirimoya': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Madeira_Flowers%2C_Fruits_and_Ferns_-_P13.jpg/330px-Madeira_Flowers%2C_Fruits_and_Ferns_-_P13.jpg',
    'Mango': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/The_Botanical_Magazine._Mango.jpg/330px-The_Botanical_Magazine._Mango.jpg',
    'Mango Extra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/The_Botanical_Magazine._Mango.jpg/330px-The_Botanical_Magazine._Mango.jpg',
    'Papaya': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg/330px-Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg',
    'Piña Normal': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/330px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg',
    'Piña Monte': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/330px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg',
    'Ciruela Roja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Plum_on_tree02.jpg/330px-Plum_on_tree02.jpg',
    'Ciruela Amarilla': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Plum_on_tree02.jpg/330px-Plum_on_tree02.jpg',
    'Ciruela Claudia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Owoce_Renkloda.jpg/330px-Owoce_Renkloda.jpg',
    'Ciruela President': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Plum_on_tree02.jpg/330px-Plum_on_tree02.jpg',
    'Cereza 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Rainier_Cherries.JPG/330px-Rainier_Cherries.JPG',
    'Cereza 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Rainier_Cherries.JPG/330px-Rainier_Cherries.JPG',
    'Albaricoque Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Turkey_apricot_RHS.jpeg/330px-Turkey_apricot_RHS.jpeg',
    'Albaricoque 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Turkey_apricot_RHS.jpeg/330px-Turkey_apricot_RHS.jpeg',
    'Albaricoque 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Turkey_apricot_RHS.jpeg/330px-Turkey_apricot_RHS.jpeg',
    'Albaricoque Rojo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Turkey_apricot_RHS.jpeg/330px-Turkey_apricot_RHS.jpeg',
    'Melocotón Calanda': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Prunus-persica_Color-variation.jpg/330px-Prunus-persica_Color-variation.jpg',
    'Melocotón Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Prunus-persica_Color-variation.jpg/330px-Prunus-persica_Color-variation.jpg',
    'Melocotón 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Prunus-persica_Color-variation.jpg/330px-Prunus-persica_Color-variation.jpg',
    'Melocotón Rojo 1': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Prunus-persica_Color-variation.jpg/330px-Prunus-persica_Color-variation.jpg',
    'Melocotón Rojo 2': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Prunus-persica_Color-variation.jpg/330px-Prunus-persica_Color-variation.jpg',
    'Melocotón Blanco': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Prunus-persica_Color-variation.jpg/330px-Prunus-persica_Color-variation.jpg',
    'Pavía Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg',
    'Pavía 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg',
    'Pavía 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg',
    'Pavía Blanco': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg',
    'Níspero': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Eriobotrya_japonica_SZ97.png/330px-Eriobotrya_japonica_SZ97.png',
    'Paraguayo Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Prunus-persica-1060223.JPG/330px-Prunus-persica-1060223.JPG',
    'Paraguayo 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Prunus-persica-1060223.JPG/330px-Prunus-persica-1060223.JPG',
    'Paraguayo 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Prunus-persica-1060223.JPG/330px-Prunus-persica-1060223.JPG',
    'Granada': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Illustration_Punica_granatum1.jpg/330px-Illustration_Punica_granatum1.jpg',
    'Granada Extra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Illustration_Punica_granatum1.jpg/330px-Illustration_Punica_granatum1.jpg',
    'Mandarina Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/330px-TangerineFruit.jpg',
    'Mandarina 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/330px-TangerineFruit.jpg',
    'Mandarina Valencia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/330px-TangerineFruit.jpg',
    'Mandarina Hoja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/330px-TangerineFruit.jpg',
    'Mandarina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/330px-TangerineFruit.jpg',
    'Mandarina Extra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/TangerineFruit.jpg/330px-TangerineFruit.jpg',
    'Naranja Mesa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
    'Naranja Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
    'Naranja Navel': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
    'Naranja Bolsa 2k': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
    'Naranja Bolsa 4k': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
    'Naranja Ripoll': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Oranges_-_whole-halved-segment.jpg/330px-Oranges_-_whole-halved-segment.jpg',
    'Pomelo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Citrus_paradisi_%28Grapefruit%2C_pink%29_white_bg.jpg/330px-Citrus_paradisi_%28Grapefruit%2C_pink%29_white_bg.jpg',
    'Sanguina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Blood_Orange_2.jpg/330px-Blood_Orange_2.jpg',
    'Manzana Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Owoce_Jab%C5%82ko.jpg/330px-Owoce_Jab%C5%82ko.jpg',
    'Golden 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Golden_Delicious_apples.jpg/330px-Golden_Delicious_apples.jpg',
    'Golden 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Golden_Delicious_apples.jpg/330px-Golden_Delicious_apples.jpg',
    'Fuji 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Apfel-Fuji.jpg/330px-Apfel-Fuji.jpg',
    'Fuji 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Apfel-Fuji.jpg/330px-Apfel-Fuji.jpg',
    'Roja 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Red_delicious_and_cross_section.jpg/330px-Red_delicious_and_cross_section.jpg',
    'Roja 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Red_delicious_and_cross_section.jpg/330px-Red_delicious_and_cross_section.jpg',
    'Royal Gala 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Gala_apples_on_cloth.jpg/330px-Gala_apples_on_cloth.jpg',
    'Royal Gala 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Gala_apples_on_cloth.jpg/330px-Gala_apples_on_cloth.jpg',
    'Verde Doncella': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Lob_Korocha1.JPG/330px-Lob_Korocha1.JPG',
    'Pink Lady': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pink_lady_and_cross_section.jpg/330px-Pink_lady_and_cross_section.jpg',
    'Granny': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Granny_smith_and_cross_section.jpg/330px-Granny_smith_and_cross_section.jpg',
    'Reineta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Deutsche_Pomologie_-_Aepfel_-_042.jpg/330px-Deutsche_Pomologie_-_Aepfel_-_042.jpg',
    'Manzana Chantecler': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Owoce_Jab%C5%82ko.jpg/330px-Owoce_Jab%C5%82ko.jpg',
    'Pera Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Owoce_Gruszka.jpg/330px-Owoce_Gruszka.jpg',
    'Conferencia 1st': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Pyrus_communis_%27Conference%27.jpg/330px-Pyrus_communis_%27Conference%27.jpg',
    'Conferencia 2nd': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Pyrus_communis_%27Conference%27.jpg/330px-Pyrus_communis_%27Conference%27.jpg',
    'Pera Agua': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Owoce_Gruszka.jpg/330px-Owoce_Gruszka.jpg',
    'Pera Limonera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Owoce_Gruszka.jpg/330px-Owoce_Gruszka.jpg',
    'Pera Roma': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Owoce_Gruszka.jpg/330px-Owoce_Gruszka.jpg',
    'Pera Ercolina': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Owoce_Gruszka.jpg/330px-Owoce_Gruszka.jpg',
    'Kiwi Oferta': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Actinidia_deliciosa_13_R.jpg/330px-Actinidia_deliciosa_13_R.jpg',
    'Kiwi Zespri': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Actinidia_deliciosa_13_R.jpg/330px-Actinidia_deliciosa_13_R.jpg',
    'Kiwi Italiano': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Actinidia_deliciosa_13_R.jpg/330px-Actinidia_deliciosa_13_R.jpg',
    'Kiwi Gold': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Actinidia_fruits.jpg/330px-Actinidia_fruits.jpg',
    'Caqui 1st': 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Persimmon_0375.jpg',
    'Caqui 2nd': 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Persimmon_0375.jpg',
    'Persimón': 'https://upload.wikimedia.org/wikipedia/commons/a/a6/Persimmon_0375.jpg',
    'Melón': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Icones_plantarum_medico-oeconomico-technologicarum_cum_earum_fructus_ususque_descriptione_%3D_%28Tab._129%29_%288096973979%29.jpg/330px-Icones_plantarum_medico-oeconomico-technologicarum_cum_earum_fructus_ususque_descriptione_%3D_%28Tab._129%29_%288096973979%29.jpg',
    'Melón Galia': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Lebensmittel-Galiamelone1-Asio.JPG/330px-Lebensmittel-Galiamelone1-Asio.JPG',
    'Melón Bollo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Icones_plantarum_medico-oeconomico-technologicarum_cum_earum_fructus_ususque_descriptione_%3D_%28Tab._129%29_%288096973979%29.jpg/330px-Icones_plantarum_medico-oeconomico-technologicarum_cum_earum_fructus_ususque_descriptione_%3D_%28Tab._129%29_%288096973979%29.jpg',
    'Membrillo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Cydonia_oblonga_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-049.jpg/330px-Cydonia_oblonga_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-049.jpg',
    'Nueces': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/20110802Walnussbaum_Plankstadt2.jpg/330px-20110802Walnussbaum_Plankstadt2.jpg',
    'Castaña': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Illustration_Castanea_sativa0.jpg/330px-Illustration_Castanea_sativa0.jpg',
    'Dátiles': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Owoce_Daktyl.jpg/330px-Owoce_Daktyl.jpg',
    'Sandía Rayada': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flore_m%C3%A9dicale_des_Antilles%2C_ou%2C_Trait%C3%A9_des_plantes_usuelles_%28Pl._305%29_%287795661744%29.jpg/330px-Flore_m%C3%A9dicale_des_Antilles%2C_ou%2C_Trait%C3%A9_des_plantes_usuelles_%28Pl._305%29_%287795661744%29.jpg',
    'Sandía Negra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flore_m%C3%A9dicale_des_Antilles%2C_ou%2C_Trait%C3%A9_des_plantes_usuelles_%28Pl._305%29_%287795661744%29.jpg/330px-Flore_m%C3%A9dicale_des_Antilles%2C_ou%2C_Trait%C3%A9_des_plantes_usuelles_%28Pl._305%29_%287795661744%29.jpg',
    'Sandía Rollo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flore_m%C3%A9dicale_des_Antilles%2C_ou%2C_Trait%C3%A9_des_plantes_usuelles_%28Pl._305%29_%287795661744%29.jpg/330px-Flore_m%C3%A9dicale_des_Antilles%2C_ou%2C_Trait%C3%A9_des_plantes_usuelles_%28Pl._305%29_%287795661744%29.jpg',
    'Uva Roja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Owoce_Winogron.jpg/330px-Owoce_Winogron.jpg',
    'Uva Blanca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Thompson_seedless_grapes.JPG/330px-Thompson_seedless_grapes.JPG',
    'Uva Extra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Owoce_Winogron.jpg/330px-Owoce_Winogron.jpg',
    'Uva sin pepita': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Thompson_seedless_grapes.JPG/330px-Thompson_seedless_grapes.JPG',
    'Garnacha': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Grenache_N.jpg/330px-Grenache_N.jpg',
    'Fresa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Strawberry_Seedling.jpg/330px-Strawberry_Seedling.jpg',
    'Fresa Extra': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Strawberry_Seedling.jpg/330px-Strawberry_Seedling.jpg',
    'Higos': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Owoce_Figa.jpg/330px-Owoce_Figa.jpg',
    'Bolsa Verde': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Trash_bin_in_Paris.jpg/330px-Trash_bin_in_Paris.jpg',
    'Bolsa Blanca': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Trash_bin_in_Paris.jpg/330px-Trash_bin_in_Paris.jpg',
    'Bolsa Rollo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Trash_bin_in_Paris.jpg/330px-Trash_bin_in_Paris.jpg',
    'Guantes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Rubber_Glove_1938_SLNSW_FL9613382.jpg/330px-Rubber_Glove_1938_SLNSW_FL9613382.jpg',
  };
}
